# Generated by Django 5.2.3 on 2025-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_employee_first_name_remove_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
